"""initial schema — all §8 tables

Hand-authored (not autogenerated — no live Postgres to diff against in this
sandbox, see api/routes and CLAUDE.md I1/§8). Mirrors api/models.py exactly.
Has NOT been applied against a real database yet; that happens in Phase 2
once DATABASE_URL points at a real Postgres/Supabase instance.

Revision ID: 0001
Revises:
Create Date: 2026-08-01
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False, unique=True),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "self_specs",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("raw_input", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("daily_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "aspirations",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("self_spec_id", sa.String(), sa.ForeignKey("self_specs.id"), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "themes",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("self_spec_id", sa.String(), sa.ForeignKey("self_specs.id"), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("alpha", sa.Float(), nullable=False),
        sa.Column("beta", sa.Float(), nullable=False),
        sa.Column("last_engaged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("momentum", sa.Float(), nullable=False),
        sa.Column("saturation", sa.Float(), nullable=False),
    )

    op.create_table(
        "candidates",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("theme_id", sa.String(), sa.ForeignKey("themes.id"), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("has_practice", sa.Boolean(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("appraised_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "decisions",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("candidate_id", sa.String(), sa.ForeignKey("candidates.id"), nullable=False),
        sa.Column("served_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("growth_score", sa.Float(), nullable=False),
        sa.Column("breakdown", sa.JSON(), nullable=False),
        sa.Column("counterfactual_id", sa.String(), sa.ForeignKey("candidates.id"), nullable=True),
        sa.Column("counterfactual_score", sa.Float(), nullable=True),
    )

    op.create_table(
        "signals",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("candidate_id", sa.String(), sa.ForeignKey("candidates.id"), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("reflection_text", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "interventions",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "events",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "clock",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("virtual_offset_seconds", sa.Integer(), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    op.drop_table("clock")
    op.drop_table("events")
    op.drop_table("interventions")
    op.drop_table("signals")
    op.drop_table("decisions")
    op.drop_table("candidates")
    op.drop_table("themes")
    op.drop_table("aspirations")
    op.drop_table("self_specs")
    op.drop_table("users")
